public class Doctor {

    private int doctorId;
    private String firstName;
    private String lastName;
    private String specialty;
    private String phone;
    // Nullable FK → use Integer, not int
    private Integer departmentId;

    public Doctor() {
    }

    // Full constructor (useful when reading from DB)
    public Doctor(int doctorId, String firstName, String lastName,
                  String specialty, String phone, Integer departmentId) {
        this.doctorId = doctorId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.specialty = specialty;
        this.phone = phone;
        this.departmentId = departmentId;
    }

    // Constructor without id (for inserts, id is generated by DB)
    public Doctor(String firstName, String lastName,
                  String specialty, String phone, Integer departmentId) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.specialty = specialty;
        this.phone = phone;
        this.departmentId = departmentId;
    }

    public int getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(int doctorId) {
        this.doctorId = doctorId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getSpecialty() {
        return specialty;
    }

    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    @Override
    public String toString() {
        String s = String.format("%-4d %-15s %-15s %-12s %-15s %-4d%n",
                doctorId, firstName, lastName, specialty, phone, departmentId);
        return s;
    }
}
