public class Doctor {

    private int doctorId;
    private String firstName;
    private String lastName;
    private String specialty;
    private String phone;
    private Integer departmentId; //Boxed because it can be null!!!!

    public Doctor() {
    }

    // Full constructor (useful when reading from DB)
    public Doctor(int doctorId, String firstName, String lastName,
                  String specialty, String phone, Integer departmentId) {
        this.doctorId = doctorId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.specialty = specialty;
        this.phone = phone;
        this.departmentId = departmentId;
    }

    // Constructor without id (for inserts, id is generated by DB)
    public Doctor(String firstName, String lastName,
                  String specialty, String phone, Integer departmentId) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.specialty = specialty;
        this.phone = phone;
        this.departmentId = departmentId;
    }

    public int getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(int doctorId) {
        this.doctorId = doctorId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        if (firstName == null || firstName.trim().isEmpty()) {
            throw new IllegalArgumentException("First name cannot be empty.");
        }
        this.firstName = firstName.trim();
    }


    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        if (lastName == null || lastName.trim().isEmpty()) {
            throw new IllegalArgumentException("Last name cannot be empty.");
        }
        this.lastName = lastName.trim();
    }

    public String getSpecialty() {
        return specialty;
    }

    public void setSpecialty(String specialty) {
        if (specialty == null || specialty.trim().isEmpty()) {
            throw new IllegalArgumentException("Specialty cannot be empty.");
        }
        this.specialty = specialty.trim();
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        if (phone != null) {
            if (!phone.matches("\\d+")) {   // digits only
                throw new IllegalArgumentException("Phone must contain digits only.");
            }
            this.phone = phone;
        } else {
            this.phone = null;
        }
    }

    public Integer getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    @Override
    public String toString() {
        String s = String.format("%-4d %-15s %-15s %-12s %-15s %-4d%n",
                doctorId, firstName, lastName, specialty, phone, departmentId);
        return s;
    }
}
